# Generated by Django 5.1 on 2025-05-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
