# Generated by Django 5.1 on 2025-05-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='nickname',
        ),
    ]
