# Generated by Django 5.1 on 2025-05-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0004_remove_review_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='webtoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='webtoons.webtoon'),
        ),
    ]
